// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PE0hF31tjPiyj9QEsUIdmgi-5Zq2vPE',
    appId: '1:431338630889:web:a95558d753a2436cb14a78',
    messagingSenderId: '431338630889',
    projectId: 'app-mobile-a1694',
    authDomain: 'app-mobile-a1694.firebaseapp.com',
    storageBucket: 'app-mobile-a1694.appspot.com',
    measurementId: 'G-JDDWFH4XJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0J7klxzWb1ysg1knJAcaB-Y8eMKzNmoY',
    appId: '1:431338630889:android:22b095be60d6d3adb14a78',
    messagingSenderId: '431338630889',
    projectId: 'app-mobile-a1694',
    storageBucket: 'app-mobile-a1694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyGQpemut-ucGCpEeZernWQzzHpQgiR5w',
    appId: '1:431338630889:ios:fd5defda25d2416fb14a78',
    messagingSenderId: '431338630889',
    projectId: 'app-mobile-a1694',
    storageBucket: 'app-mobile-a1694.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyGQpemut-ucGCpEeZernWQzzHpQgiR5w',
    appId: '1:431338630889:ios:fd5defda25d2416fb14a78',
    messagingSenderId: '431338630889',
    projectId: 'app-mobile-a1694',
    storageBucket: 'app-mobile-a1694.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3PE0hF31tjPiyj9QEsUIdmgi-5Zq2vPE',
    appId: '1:431338630889:web:2d9654193b455c8fb14a78',
    messagingSenderId: '431338630889',
    projectId: 'app-mobile-a1694',
    authDomain: 'app-mobile-a1694.firebaseapp.com',
    storageBucket: 'app-mobile-a1694.appspot.com',
    measurementId: 'G-MG9MB6BRE6',
  );
}
